# Unique name for this workflow
name: Rhythm - For loop for Scratch Org Creation

# Definition when the workflow should run
on:
  workflow_dispatch:
    inputs:
     scratch-org_count: 
      #Count for number of scratch-org which needs to be created
      default: 'scratch-org'
      required: true
                        
# Jobs to be done
jobs:
  - name: job1
    run: |
        set +e
        i=0
        if [ i < ${{github.event.inputs.scratch-number}} ]; 
        then
  	   echo i++
           echo "Creating Scratch Org"
        else
            echo "Required no.of scratch orgs have been created"
 	fi
        exit $status
    
  - name: job2
    needs: job1
    uses: .github/workflows/CPQ - ScratchOrg Creation and Package Deployment.yml

